<?php
// ============================================================
// cron-weekly.php - Run every Monday at 9 AM
// Cron: 0 9 * * 1 php /path/to/seo-system/cron-weekly.php
// ============================================================
require_once __DIR__ . '/includes/mailer.php';

$db = getDB();
$log = [];
$log[] = '[' . date('Y-m-d H:i:s') . '] Weekly cron started';

$projects = $db->query("SELECT * FROM projects")->fetchAll();

foreach ($projects as $project) {
    $clientEmail = trim($project['email'] ?? '');
    $log[] = "Weekly report for project #{$project['id']}: {$project['target_keyword']}";

    if (empty($clientEmail)) {
        $log[] = "  → Skipped email: No contact email address configured for this client profile.";
        continue;
    }

    // Get weekly stats
    $weekAgo = date('Y-m-d', strtotime('-7 days'));
    $today   = date('Y-m-d');

    $rankNow  = $db->prepare("SELECT `rank` FROM seo_reports WHERE project_id=? AND `rank` > 0 ORDER BY report_date DESC LIMIT 1");
    $rankNow->execute([$project['id']]);
    $rankNow = $rankNow->fetchColumn() ?: 0;

    $rankWeekAgo = $db->prepare("SELECT `rank` FROM seo_reports WHERE project_id=? AND `rank` > 0 AND report_date <= ? ORDER BY report_date DESC LIMIT 1");
    $rankWeekAgo->execute([$project['id'], $weekAgo]);
    $rankWeekAgo = $rankWeekAgo->fetchColumn() ?: 0;

    $newBacklinks = $db->prepare("SELECT COUNT(*) FROM backlinks WHERE project_id=? AND status='created' AND created_at >= ?");
    $newBacklinks->execute([$project['id'], $weekAgo]);
    $newBacklinks = $newBacklinks->fetchColumn();

    $seoScore = $db->prepare("SELECT seo_score FROM seo_reports WHERE project_id=? ORDER BY report_date DESC LIMIT 1");
    $seoScore->execute([$project['id']]);
    $seoScore = $seoScore->fetchColumn() ?: 0;

    $rankChange = $rankWeekAgo > 0 && $rankNow > 0 ? $rankWeekAgo - $rankNow : 0;

    $log[] = "  Rank: #{$rankNow} (change: " . ($rankChange >= 0 ? "+$rankChange" : "$rankChange") . ")";
    $log[] = "  New backlinks this week: {$newBacklinks}";
    $log[] = "  SEO Score: {$seoScore}/100";

    // Generate weekly report HTML
    $reportHtml = "
    <div style='font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;'>
        <h2 style='color: #2b6cb0;'>Weekly SEO Report</h2>
        <p><strong>Keyword:</strong> " . clean($project['target_keyword']) . "</p>
        <p><strong>Website:</strong> " . clean($project['website_url']) . "</p>
        <p><strong>Reporting Week:</strong> {$weekAgo} to {$today}</p>
        <hr style='border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;'>
        <table border='0' cellpadding='10' cellspacing='0' style='width: 100%; border-collapse: collapse;'>
          <thead>
            <tr style='background-color: #f7fafc; border-bottom: 2px solid #edf2f7;'>
              <th align='left'>Metric</th>
              <th align='left'>Value</th>
              <th align='left'>Status</th>
            </tr>
          </thead>
          <tbody>
            <tr style='border-bottom: 1px solid #edf2f7;'>
              <td><strong>Google Rank</strong></td>
              <td>#" . ($rankNow ?: 'N/A') . "</td>
              <td>" . ($rankChange > 0 ? "<span style='color: green;'>↑ Improved by " . abs($rankChange) . " spots</span>" : ($rankChange < 0 ? "<span style='color: red;'>↓ Dropped by " . abs($rankChange) . " spots</span>" : "No change")) . "</td>
            </tr>
            <tr style='border-bottom: 1px solid #edf2f7;'>
              <td><strong>SEO Optimization Score</strong></td>
              <td>{$seoScore}/100</td>
              <td>-</td>
            </tr>
            <tr style='border-bottom: 1px solid #edf2f7;'>
              <td><strong>New Backlinks Created</strong></td>
              <td>{$newBacklinks} backlinks</td>
              <td>-</td>
            </tr>
          </tbody>
        </table>
        <p style='margin-top: 30px; font-size: 12px; color: #a0aec0; text-align: center;'>This is an automated weekly SEO report generated by our SEO System.</p>
    </div>
    ";

    // Send email to client
    $sent = sendSmtpMail($clientEmail, "Weekly SEO Performance: " . $project['target_keyword'], $reportHtml);
    if ($sent) {
        $log[] = "  → Weekly report emailed to {$clientEmail} successfully.";
    } else {
        $log[] = "  → Email failed to send to {$clientEmail} (Check SMTP configuration).";
    }
}

$log[] = '[' . date('Y-m-d H:i:s') . '] Weekly cron completed';

$logFile = __DIR__ . '/logs/cron-weekly-' . date('Y-m-d') . '.log';
if (!is_dir(__DIR__ . '/logs')) mkdir(__DIR__ . '/logs', 0755, true);
file_put_contents($logFile, implode("\n", $log) . "\n");

echo implode("\n", $log);
?>
